dist: trusty
language: php

php:
  - 7.0
  - 7.1

before_script:
  - sudo chmod -R 755 modules/ application/ system/

script: 
  - phpunit --bootstrap=modules/unittest/bootstrap.php modules/unittest/tests.php

notifications:
  email: false
